# see https://fabricmc.net/develop/ for new versions
[versions]
    java = "21"
    kotlin = "2.3.21"
    fabric_loom = "1.16-SNAPSHOT"
    iridium = "4.0.0"
    # Dependencies
    minecraft = "1.21.1"
    fabric_loader = "0.19.2"
    fabric_api = "0.116.12+1.21.1"
    fabric_kotlin = "1.13.11+kotlin.2.3.21"
    fzzy_config = "0.7.6+1.21"
    voidlib = "0.1.0-alpha.2"
    # Compatibility
    # Runtime
    modmenu = "11.0.3"
    emi = "1.1.24+1.21.1"
    # Testing
    creative_works = "0.6.1+1.21.1"

[libraries]
    # Dependencies
    minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
    fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
    fabric_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_kotlin" }
    fzzy-config = { module = "me.fzzyhmstrs:fzzy_config", version.ref = "fzzy_config" }
    voidlib = { module = "org.teamvoided:voidlib", version.ref = "voidlib" }
    # Compatibility
    # Runtime
    modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
    emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
    # Testing
    creative-works = { module = "org.teamvoided:creative_works", version.ref = "creative_works" }
[bundles]
    cw = [ "creative-works" ]

[plugins]
    kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
    # kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
    fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric_loom" }
    iridium = { id = "org.teamvoided.iridium", version.ref = "iridium" }
    iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium" }
    iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }
