mod_name = "Top Hats and Monocles"
mod_id = "top_hats_and_monocles"
mod_group = "com.theendercore"
mod_version = "0.1.0"
mod_description = "Hats, People, Hats!"
github_repo = "Teamvoided/TopHatsAndMonocles"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "TheEnderCore" ]
license = "MIT"
version_range = ">=1.21.11 <26.1"
